- name: "ensure spark history directory exists in hdfs" 
  command: "{{ hadoop_home}}/bin/hdfs dfs -mkdir -p /spark/history"
  register: mk_hist_dir
  changed_when: mk_hist_dir.rc != 0
- name: "start spark history server"
  command: "{{ spark_home }}/sbin/start-history-server.sh"
  register: sparkhist
  changed_when: "'org.apache.spark.deploy.history.HistoryServer running as process' not in sparkhist.stdout"
  failed_when: sparkhist.rc != 0 and 'org.apache.spark.deploy.history.HistoryServer running as process' not in sparkhist.stdout
