- name: "ensure hostname is correct"
  hostname: name={{ inventory_hostname }}
- name: "ensure /etc/hosts is correct"
  template: src=roles/common/templates/etc_hosts dest=/etc/hosts owner=root group=root mode=0644
