- name: "enable epel yum repo" 
  yum: name=epel-release state=present
- name: "install packages"
  yum: name={{ item }} state=present
  with_items:
    - vim
    - git
    - wget
    - gcc-c++
    - collectd
    - screen
    - patch
- name: "create install directory on all hosts"
  file: path={{ install_dir }} state=directory owner={{ cluster_user }} group={{ cluster_user }}
- name: "install java & maven"
  unarchive: src={{ tarballs_dir }}/{{ item.tarball }} dest={{ install_dir }} creates={{ item.install }}
  with_items:
    - { tarball: "{{ java_tarball }}", install: "{{ java_home }}" } 
    - { tarball: "{{ maven_tarball }}", install: "{{ maven_home }}" } 
- name: "set correct owner & group for java & maven home"
  file: path={{ item }} recurse=yes owner={{ cluster_user }} group={{ cluster_user}}
  with_items:
    - "{{ java_home }}"
    - "{{ maven_home }}"
- name: "configure collectd"
  template: src=collectd.conf dest=/etc/collectd.conf
  when: "'metrics' in groups"
  notify:
    - restart collectd
- name: "ensure collectd is running (and enable it at boot)"
  service: name=collectd state=started enabled=yes
  when: "'metrics' in groups"
