- hosts: all
  roles:
    - accumulo
- hosts: accumulomaster
  tasks:
    - include: roles/accumulo/tasks/init-accumulo.yml
  handlers:
    - include: roles/accumulo/handlers/init-accumulo.yml
- hosts: accumulo
  tasks:
    - include: roles/accumulo/tasks/start-accumulo.yml
