- hosts: nodes
  sudo: yes
  tasks:
  - include: roles/common/tasks/hosts.yml
- hosts: proxy
  roles:
    - proxy
- hosts: all
  sudo: yes
  roles:
    - common
  tasks:
  - include: roles/common/tasks/ssh.yml
  - include: roles/common/tasks/os.yml
  - include: roles/common/tasks/drives.yml
  handlers:
  - include: roles/common/handlers/os.yml
- hosts: metrics
  sudo: yes
  roles:
    - influxdb
    - grafana
- hosts: all
  roles:
    - spark
    - hadoop
    - zookeeper
    - accumulo
- hosts: namenode
  tasks:
    - include: roles/hadoop/tasks/start-hdfs.yml
- hosts: resourcemanager
  tasks:
    - include: roles/hadoop/tasks/start-yarn.yml
    - include: roles/spark/tasks/start-spark-history.yml
- hosts: zookeepers
  tasks:
    - include: roles/zookeeper/tasks/start-zookeeper.yml
- hosts: accumulomaster
  tasks:
    - include: roles/accumulo/tasks/init-accumulo.yml
  handlers:
    - include: roles/accumulo/handlers/init-accumulo.yml
- hosts: accumulo
  tasks:
    - include: roles/accumulo/tasks/start-accumulo.yml
- hosts: fluo
  roles:
    - fluo
