- hosts: metrics
  sudo: yes
  tasks:
  - name: "stop influxdb and grafana"
    service: name={{ item }} state=stopped
    with_items:
      - influxdb
      - grafana-server
  - name: "wipe influxdb data"
    file: path={{ default_data_dirs[0] }}/influxdb state=absent
  - name: "wipe grafana db"
    file: path=/var/lib/grafana/grafana.db state=absent
- include: kill.yml
- hosts: hadoop
  tasks:
  - name: "wipe hadoop data"
    file: path={{item}}/hadoop state=absent
    with_items: "{{ worker_data_dirs }}"
  - name: "remove hadoop logs"
    shell: rm -rf {{ hadoop_prefix }}/logs/*
- hosts: zookeepers
  tasks:
  - name: "wipe zookeeper data"
    file: path={{ default_data_dirs[0] }}/zookeeper state=absent
  - name: "remove zookeeper logs"
    file: path={{ zookeeper_home }}/zookeeper.out state=absent
- hosts: accumulo
  tasks:
  - name: "remove accumulo logs"
    shell: rm -rf {{ accumulo_home }}/logs/*
